const client=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let editing=null,products=[];const sectors=['Chocolates','Confeitaria','Sorveteria','Restaurante','Ocidental','Resfriados','Congelados'];const $=id=>document.getElementById(id);const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function init(){const {data:{session}}=await client.auth.getSession();if(!session)return location.href='login.html';const {data:p}=await client.from('profiles').select('role,email').eq('id',session.user.id).single();if(!p||p.role!=='admin'){ $('app').innerHTML='<div class="panel"><h2>Acesso negado</h2><p>Sua conta não é administradora.</p><a class="secondary" href="index.html">Voltar</a></div>';return}panel()}
function panel(){$('app').innerHTML=`<div class="panel"><button class="primary" style="float:right" id="logout">Sair</button><h2>Gerenciar site</h2><div class="tabs"><button onclick="showTab('prod')">Produtos</button><button onclick="showTab('promo')">Promoções</button><button onclick="showTab('settings')">Configurações</button></div><div id="tab"></div></div>`;$('logout').onclick=async()=>{await client.auth.signOut();location.href='index.html'};showTab('prod')}
function showTab(t){if(t==='prod')return productTab();if(t==='promo')return promoTab();settingsTab()}
function productTab(){$('tab').innerHTML=`<h3>Produtos</h3><form class="form" id="pf"><label>Nome<input id="name" required></label><label>Preço<input id="price" type="number" step="0.01" required></label><label>Setor<select id="sector">${sectors.map(s=>`<option>${s}</option>`).join('')}</select></label><label>Imagem<input id="image" type="file" accept="image/*"></label><label>Estoque<select id="stock"><option value="true">Com estoque</option><option value="false">Sem estoque</option></select></label><label>Preço promocional (opcional)<input id="promo" type="number" step="0.01" min="0"></label><button class="primary">Salvar produto</button></form><div id="list"></div>`;$('pf').onsubmit=save;load()}
async function load(){const {data}=await client.from('products').select('*').order('created_at',{ascending:false});products=data||[];$('list').innerHTML=products.map(p=>`<div class="row"><img class="thumb" src="${esc(p.image_url||'')}" alt=""><div class="grow"><b>${esc(p.name)}</b><br><small>${esc(p.sector)} • ${money(p.price)} ${p.promo_price!=null?'• PROMO '+money(p.promo_price):''} • ${p.in_stock===false?'SEM ESTOQUE':'ESTOQUE'}</small></div><button class="secondary" onclick="edit('${p.id}')">Editar</button><button class="danger" onclick="removeProduct('${p.id}')">Excluir</button></div>`).join('')}
async function upload(file){if(!file)return null;const path=`${crypto.randomUUID()}.${file.name.split('.').pop().toLowerCase()}`;const {error}=await client.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return client.storage.from('product-images').getPublicUrl(path).data.publicUrl}
async function save(e){e.preventDefault();const payload={name:$('name').value.trim(),price:Number($('price').value),sector:$('sector').value,in_stock:$('stock').value==='true',promo_price:$('promo').value?Number($('promo').value):null,active:true,updated_at:new Date().toISOString()};const f=$('image').files[0];try{if(f)payload.image_url=await upload(f);let r=editing?await client.from('products').update(payload).eq('id',editing):await client.from('products').insert(payload);if(r.error)throw r.error;editing=null;productTab();alert('Salvo!')}catch(e){alert('Erro: '+e.message)}}
function edit(id){const p=products.find(x=>x.id===id);editing=id;$('name').value=p.name;$('price').value=p.price;$('sector').value=p.sector;$('stock').value=String(p.in_stock!==false);$('promo').value=p.promo_price??'';window.scrollTo({top:0,behavior:'smooth'})}
async function removeProduct(id){if(!confirm('Excluir?'))return;await client.from('products').delete().eq('id',id);load()}
async function promoTab(){const {data}=await client.from('products').select('*').order('name');$('tab').innerHTML='<h3>Promoções</h3><p>Defina o preço promocional. Deixe vazio para retirar da promoção.</p>'+data.map(p=>`<div class="row"><div class="grow"><b>${esc(p.name)}</b><br>${money(p.price)}</div><input id="pr_${p.id}" type="number" step="0.01" value="${p.promo_price??''}" placeholder="Preço oferta"><button class="primary" onclick="setPromo('${p.id}')">Salvar</button></div>`).join('')}
async function setPromo(id){const v=$(`pr_${id}`).value;const {error}=await client.from('products').update({promo_price:v?Number(v):null,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else alert('Promoção atualizada!')}
async function settingsTab(){const {data}=await client.from('site_settings').select('*').eq('key','whatsapp_orders').maybeSingle();$('tab').innerHTML=`<h3>Configurações</h3><label>WhatsApp para pedidos<input id="wa" value="${esc(data?.value||'5581971178793')}" placeholder="5581999999999"></label><button class="primary" onclick="saveWa()">Salvar WhatsApp</button>`}
async function saveWa(){let v=$('wa').value.replace(/\D/g,'');const {error}=await client.from('site_settings').upsert({key:'whatsapp_orders',value:v});if(error)alert(error.message);else alert('WhatsApp salvo!')}
init();
