const client=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let editing=null,products=[],banners=[],settings={};
const sectors=["Chocolates","Confeitaria","Sorveteria","Restaurante","Ocidental","Resfriados","Congelados"];const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));const $=id=>document.getElementById(id);const money=v=>Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
async function init(){const {data:{session}}=await client.auth.getSession();if(!session)return login();const {data:profile}=await client.from("profiles").select("role,email").eq("id",session.user.id).single();if(!profile||profile.role!=="admin")return denied();panel()}
function login(){$("app").innerHTML=`<div class="panel login"><h2>Login do administrador</h2><p>Entre para gerenciar o catálogo.</p><input id="email" type="email" placeholder="E-mail"><input id="pass" type="password" placeholder="Senha"><button class="primary" id="loginBtn">Entrar</button><p id="msg"></p></div>`;$('loginBtn').onclick=async()=>{let {error}=await client.auth.signInWithPassword({email:$('email').value.trim(),password:$('pass').value});if(error)$('msg').textContent=error.message;else location.reload()}}
function denied(){$("app").innerHTML=`<div class="panel"><h2>Acesso negado</h2><p>Seu usuário não possui permissão de administrador.</p><button class="primary" onclick="logout()">Sair</button></div>`}
async function logout(){await client.auth.signOut();location.reload()}
async function panel(){$("app").innerHTML=`<div class="panel"><button class="primary" style="float:right" onclick="logout()">Sair</button><h2>Administração</h2><div class="tabs"><button onclick="tab('products')">Produtos</button><button onclick="tab('promos')">Promoções</button><button onclick="tab('banners')">Banners</button><button onclick="tab('settings')">WhatsApp</button></div><div id="adminContent"></div></div>`;tab('products')}
function tab(t){if(t==='products')productsTab();if(t==='promos')promosTab();if(t==='banners')bannersTab();if(t==='settings')settingsTab()}
async function productsTab(){let {data,error}=await client.from('products').select('*').order('created_at',{ascending:false});products=data||[];$('adminContent').innerHTML=`<form class="form" id="productForm"><h3 id="formTitle">Adicionar produto</h3><label>Nome<input id="name" required></label><label>Código<input id="productCode" maxlength="6" inputmode="numeric"></label><label>Preço<input id="price" type="number" step="0.01" min="0" required></label><label>Setor<select id="sector">${sectors.map(s=>`<option>${s}</option>`).join('')}</select></label><label>Foto<input id="image" type="file" accept="image/*"></label><label class="check"><input id="active" type="checkbox" checked> Aparecer no catálogo</label><label class="check"><input id="inStock" type="checkbox" checked> Com estoque</label><div><button class="primary" type="submit" id="save">Adicionar produto</button><button type="button" class="secondary" onclick="clearForm()">Limpar</button></div></form><div id="productList"></div>`;$('productForm').onsubmit=saveProduct;renderProductList()}
function renderProductList(){$('productList').innerHTML=products.map(p=>`<div class="row"><img class="thumb" src="${esc(p.image_url||'')}" alt=""><div class="grow"><b>${esc(p.name)}</b><br><small>${esc(p.sector)} • ${money(p.price)} • ${p.in_stock?'Com estoque':'SEM ESTOQUE'} • ${p.promotion?'OFERTA':''}</small></div><button class="secondary" onclick="editProduct('${p.id}')">✏️</button><button class="danger" onclick="removeProduct('${p.id}')">🗑️</button></div>`).join('')}
async function upload(file){if(!file)return null;let ext=file.name.split('.').pop().toLowerCase(),path=`${crypto.randomUUID()}.${ext}`;let {error}=await client.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return client.storage.from('product-images').getPublicUrl(path).data.publicUrl}
async function saveProduct(e){e.preventDefault();let name=$('name').value.trim(),code=$('productCode').value.trim(),price=Number($('price').value),sector=$('sector').value,active=$('active').checked,inStock=$('inStock').checked,file=$('image').files[0];if(!name||!Number.isFinite(price))return alert('Preencha nome e preço.');try{let image_url=editing?.image_url||null;if(file)image_url=await upload(file);let payload={name,product_code:code||null,price,sector,active,in_stock:inStock,image_url,updated_at:new Date().toISOString()};let res=editing?await client.from('products').update(payload).eq('id',editing.id):await client.from('products').insert(payload);if(res.error)throw res.error;alert(editing?'Produto atualizado!':'Produto cadastrado!');clearForm();productsTab()}catch(err){alert('Erro: '+err.message)}}
function editProduct(id){let p=products.find(x=>x.id===id);if(!p)return;editing=p;$("name").value=p.name;$("productCode").value=p.product_code||'';$("price").value=p.price;$("sector").value=p.sector;$("active").checked=p.active;$("inStock").checked=p.in_stock;$('save').textContent='Salvar alterações';$('formTitle').textContent='Editar produto';window.scrollTo({top:0,behavior:'smooth'})}
function clearForm(){editing=null;let f=$('productForm');if(f){f.reset();$('active').checked=true;$('inStock').checked=true;$('save').textContent='Adicionar produto';$('formTitle').textContent='Adicionar produto'}}
async function removeProduct(id){if(!confirm('Excluir este produto?'))return;let {error}=await client.from('products').delete().eq('id',id);if(error)alert(error.message);else productsTab()}
async function promosTab(){let {data}=await client.from('products').select('*').order('name');products=data||[];$('adminContent').innerHTML=`<h3>Colocar produtos em promoção</h3><p>Marque a oferta e informe o preço antigo.</p><div id="promoList"></div>`;$('promoList').innerHTML=products.map(p=>`<div class="promoAdmin"><div class="grow"><b>${esc(p.name)}</b><small>${money(p.price)}</small></div><label><input type="checkbox" ${p.promotion?'checked':''} onchange="togglePromo('${p.id}',this.checked)"> Oferta</label><input type="number" step="0.01" min="0" value="${p.old_price??''}" placeholder="Preço antigo" onchange="setOldPrice('${p.id}',this.value)"></div>`).join('')}
async function togglePromo(id,on){let p=products.find(x=>x.id===id);let {error}=await client.from('products').update({promotion:on,old_price:on?(p.old_price||p.price):null,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message)}
async function setOldPrice(id,v){let {error}=await client.from('products').update({old_price:v?Number(v):null,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message)}
async function bannersTab(){let {data}=await client.from('banners').select('*').order('sort_order');banners=data||[];$('adminContent').innerHTML=`<form class="form" id="bannerForm"><h3>Novo banner</h3><label>Título<input id="bannerTitle" placeholder="Ex.: Novidades da semana"></label><label>Imagem<input id="bannerImage" type="file" accept="image/*" required></label><label>Ordem<input id="bannerOrder" type="number" value="0"></label><label class="check"><input id="bannerActive" type="checkbox" checked> Ativo</label><button class="primary">Adicionar banner</button></form><div id="bannerList"></div>`;$('bannerForm').onsubmit=saveBanner;renderBannersAdmin()}
async function saveBanner(e){e.preventDefault();try{let f=$('bannerImage').files[0];let url=await upload(f);let {error}=await client.from('banners').insert({title:$('bannerTitle').value.trim(),image_url:url,sort_order:Number($('bannerOrder').value)||0,active:$('bannerActive').checked});if(error)throw error;alert('Banner adicionado!');bannersTab()}catch(err){alert('Erro: '+err.message)}}
function renderBannersAdmin(){$('bannerList').innerHTML=banners.map(b=>`<div class="row"><img class="thumb" src="${esc(b.image_url)}"><div class="grow"><b>${esc(b.title||'Banner')}</b><br><small>${b.active?'Ativo':'Oculto'}</small></div><button class="secondary" onclick="toggleBanner('${b.id}',${!b.active})">${b.active?'Ocultar':'Ativar'}</button><button class="danger" onclick="deleteBanner('${b.id}')">🗑️</button></div>`).join('')}
async function toggleBanner(id,on){await client.from('banners').update({active:on}).eq('id',id);bannersTab()}async function deleteBanner(id){if(!confirm('Excluir banner?'))return;await client.from('banners').delete().eq('id',id);bannersTab()}
async function settingsTab(){let {data}=await client.from('site_settings').select('*');settings=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));$('adminContent').innerHTML=`<form class="form" id="settingsForm"><h3>WhatsApp para pedidos</h3><p>Digite somente números ou no formato (81) 97117-8793.</p><label>Número<input id="whatsapp" value="${esc(settings.whatsapp||'81971178793')}" placeholder="81971178793" required></label><button class="primary">Salvar WhatsApp</button></form>`;$('settingsForm').onsubmit=saveSettings}
async function saveSettings(e){e.preventDefault();let value=$('whatsapp').value.replace(/\D/g,'');if(value.length<10)return alert('Informe um WhatsApp válido.');let {error}=await client.from('site_settings').upsert({key:'whatsapp',value});if(error)alert(error.message);else alert('WhatsApp salvo!')}
init();
