const client=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
let editing=null,products=[],currentUserId=null,currentAdminEmail='';
const sectors=['Chocolates','Confeitaria','Sorveteria','Padaria','Restaurante','Ocidental','Frios','Congelados'];
const $=id=>document.getElementById(id);
const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const statusLabel={received:'Novo',ready_payment:'Pronto para pagar',paid:'Pago',completed:'Finalizado',cancelled:'Cancelado'};
const statusClass={received:'status-new',ready_payment:'status-ready',paid:'status-paid',completed:'status-done',cancelled:'status-cancelled'};
async function init(){
  const {data:{session}}=await client.auth.getSession();
  if(!session)return location.href='login.html';
  currentUserId=session.user.id;
  const {data:p,error}=await client.from('profiles').select('role,email').eq('id',session.user.id).single();
  if(error||!p||p.role!=='admin'){$('app').innerHTML='<div class="denied"><h2>Acesso negado</h2><p>Sua conta não é administradora.</p><a href="index.html">Voltar ao catálogo</a></div>';return}
  currentAdminEmail=p.email||session.user.email||'';
  panel();
}
function panel(){
  $('app').innerHTML=`<div class="admin-shell">
    <aside class="sidebar"><div class="side-brand"><img src="logo-macrofood.jpg"><div><b>MacroFood</b><span>Painel Administrativo</span></div><button class="sidebar-close" type="button" aria-label="Fechar menu" onclick="closeMobileSidebar()">×</button></div>
      <nav class="side-nav">
        <button onclick="showTab('dashboard')" data-nav="dashboard">⌂ <span>Dashboard</span></button>
        <button onclick="showTab('prod')" data-nav="prod">◈ <span>Produtos</span></button>
        <button onclick="showTab('categories')" data-nav="categories">▣ <span>Categorias</span></button>
        <button onclick="showTab('promo')" data-nav="promo">◇ <span>Promoções</span></button>
        <button onclick="showTab('banners')" data-nav="banners">▧ <span>Banners</span></button>
        <button onclick="showTab('clients')" data-nav="clients">♟ <span>Clientes</span></button>
        <button onclick="showTab('orders')" data-nav="orders">🛍 <span>Pedidos</span><b id="orderBadge" class="nav-badge hidden">0</b></button>
        <button onclick="showTab('suggestions')" data-nav="suggestions">💡 <span>Sugestões</span><b id="suggestionBadge" class="nav-badge hidden">0</b></button>
        <button onclick="showTab('support')" data-nav="support">💬 <span>Suporte</span><b id="supportBadge" class="nav-badge hidden">0</b></button>
        <button onclick="showTab('settings')" data-nav="settings">⚙ <span>Configurações</span></button>
      </nav>
      <div class="side-bottom"><div class="admin-note">🛡<br><b>Área Administrativa</b><small>Somente administradores possuem acesso a esta área.</small></div><button class="logout-side" id="logout">↪ <span>Sair</span></button></div>
    </aside>
    <div class="sidebar-backdrop" onclick="closeMobileSidebar()" aria-hidden="true"></div>
    <section class="admin-main"><header class="admin-top"><button class="menu-btn" type="button" aria-label="Abrir menu" onclick="toggleMobileSidebar()">☰</button><div class="top-spacer"></div><div class="admin-profile"><div class="avatar">●</div><div><b>Administrador</b><small>${esc(currentAdminEmail)}</small></div><span>⌄</span></div></header><main class="admin-content"><div id="tab"></div></main></section>
  </div>`;
  $('logout').onclick=async()=>{await client.auth.signOut();location.href='index.html'};
  showTab('dashboard');
  refreshOrderBadge();
  setInterval(refreshOrderBadge,30000);setInterval(refreshSupportBadge,30000);
}
function nav(t){document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===t));closeMobileSidebar()}
function toggleMobileSidebar(){document.body.classList.toggle('sidebar-open')}
function closeMobileSidebar(){document.body.classList.remove('sidebar-open')}
async function showTab(t){nav(t);if(t==='dashboard')return dashboardTab();if(t==='prod')return productTab();if(t==='categories')return categoriesTab();if(t==='promo')return promoTab();if(t==='banners')return bannersTab();if(t==='clients')return clientsTab();if(t==='orders')return ordersTab();if(t==='suggestions')return suggestionsTab();if(t==='support')return supportTab();return settingsTab()}
function pageTitle(title,subtitle){return `<div class="page-head"><div><h1>${title}</h1><p>${subtitle}</p></div></div>`}
async function dashboardTab(){
  const [{count:clientCount},{count:productCount},{count:orderCount},{count:newCount}]=await Promise.all([
    client.from('profiles').select('id',{count:'exact',head:true}),client.from('products').select('id',{count:'exact',head:true}).eq('active',true),client.from('orders').select('id',{count:'exact',head:true}),client.from('orders').select('id',{count:'exact',head:true}).eq('status','received')]);
  const {data:recent}=await client.from('orders').select('*').order('created_at',{ascending:false}).limit(5);
  $('tab').innerHTML=`${pageTitle('Dashboard','Visão geral da sua loja.')}
  <div class="metric-grid"><div class="metric orange"><span>👥</span><div><small>Total de Clientes</small><strong>${clientCount||0}</strong><em>Contas cadastradas</em></div></div><div class="metric green"><span>●</span><div><small>Produtos ativos</small><strong>${productCount||0}</strong><em>Disponíveis no catálogo</em></div></div><div class="metric blue"><span>🛍</span><div><small>Total de pedidos</small><strong>${orderCount||0}</strong><em>Pedidos recebidos</em></div></div><div class="metric purple"><span>⏱</span><div><small>Pedidos novos</small><strong>${newCount||0}</strong><em>Aguardando conferência</em></div></div></div>
  <div class="panel-card"><div class="card-head"><div><h3>Pedidos recentes</h3><p>Últimos pedidos recebidos pelo site.</p></div><button class="outline-btn" onclick="showTab('orders')">Ver todos</button></div>${recent?.length?recent.map(orderRow).join(''):'<div class="empty-state">Nenhum pedido ainda.</div>'}</div>`;
}
function orderRow(o){return `<div class="order-mini"><div class="order-icon">🛍</div><div class="grow"><b>Pedido #${o.order_number}</b><small>${esc(o.customer_name)} • ${esc(o.customer_phone)}</small></div><span class="status ${statusClass[o.status]||''}">${statusLabel[o.status]||o.status}</span><strong>${money(o.total)}</strong></div>`}
async function refreshOrderBadge(){const {count}=await client.from('orders').select('id',{count:'exact',head:true}).eq('status','received');const b=$('orderBadge');if(!b)return;b.textContent=count||0;b.classList.toggle('hidden',!count)}
function productTab(){
  $('tab').innerHTML=`${pageTitle('Produtos','Gerencie os produtos exibidos no catálogo.')}
  <div class="panel-card"><div class="card-head"><div><h3>${editing?'Editar produto':'Cadastrar produto'}</h3><p>Preencha os dados do produto.</p></div></div><form class="form" id="pf"><label>Nome<input id="name" required></label><label>Preço normal<input id="price" type="number" step="0.01" min="0" required></label><label>Setor<select id="sector">${sectors.map(s=>`<option>${s}</option>`).join('')}</select></label><label>Imagem<input id="image" type="file" accept="image/*"></label><label>Estoque<select id="stock"><option value="true">Com estoque</option><option value="false">Sem estoque</option></select></label><label>Preço promocional<input id="promo" type="number" step="0.01" min="0" placeholder="Opcional"></label><label class="featured-toggle"><input id="featured" type="checkbox"><span>⭐ Colocar este produto em destaque no catálogo</span></label><div class="form-actions full"><button class="primary">${editing?'Salvar alterações':'Cadastrar produto'}</button>${editing?'<button type="button" class="secondary" onclick="editing=null;productTab()">Cancelar</button>':''}</div></form></div><div class="panel-card"><div class="card-head"><div><h3>Produtos cadastrados</h3></div></div><div id="list"></div></div>`;
  $('pf').onsubmit=save;load();
}
async function load(){const {data,error}=await client.from('products').select('*').order('created_at',{ascending:false});if(error){$('list').innerHTML='<div class="notice">'+esc(error.message)+'</div>';return}products=data||[];$('list').innerHTML=products.length?products.map(p=>`<div class="product-admin-row"><img class="thumb" src="${esc(p.image_url||'')}" alt=""><div class="grow"><b>${esc(p.name)} ${p.is_featured?'<span class=\"featured-admin-badge\">⭐ Destaque</span>':''}</b><small>${esc(p.sector)} • ${money(p.price)} ${p.promo_price!=null?'• Promo '+money(p.promo_price):''} • ${p.in_stock===false?'Sem estoque':'Em estoque'}</small></div><button class="outline-btn" onclick="edit('${p.id}')">Editar</button><button class="danger" onclick="removeProduct('${p.id}')">Excluir</button></div>`).join(''):'<div class="empty-state">Nenhum produto cadastrado.</div>'}
async function upload(file){if(!file)return null;const path=`${crypto.randomUUID()}.${file.name.split('.').pop().toLowerCase()}`;const {error}=await client.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return client.storage.from('product-images').getPublicUrl(path).data.publicUrl}
async function save(e){e.preventDefault();const price=Number($('price').value),promo=$('promo').value?Number($('promo').value):null;if(promo!==null&&promo>=price)return alert('O preço promocional deve ser menor que o preço normal.');const payload={name:$('name').value.trim(),price,sector:$('sector').value,in_stock:$('stock').value==='true',promo_price:promo,is_featured:$('featured').checked,active:true,updated_at:new Date().toISOString()};const f=$('image').files[0];try{if(f)payload.image_url=await upload(f);const r=editing?await client.from('products').update(payload).eq('id',editing):await client.from('products').insert(payload);if(r.error)throw r.error;editing=null;productTab();alert('Produto salvo!')}catch(e){alert('Erro: '+e.message)}}
function edit(id){const p=products.find(x=>x.id===id);if(!p)return;editing=id;productTab();setTimeout(()=>{$('name').value=p.name;$('price').value=p.price;$('sector').value=p.sector;$('stock').value=String(p.in_stock!==false);$('promo').value=p.promo_price??'';$('featured').checked=p.is_featured===true;window.scrollTo({top:0,behavior:'smooth'})},0)}
async function removeProduct(id){if(!confirm('Excluir este produto?'))return;const {error}=await client.from('products').delete().eq('id',id);if(error)alert(error.message);else load()}
async function categoriesTab(){ $('tab').innerHTML=`${pageTitle('Categorias','As categorias disponíveis no catálogo.') }<div class="panel-card"><div class="category-grid">${['Chocolates','Confeitaria','Sorveteria','Padaria','Restaurante','Ocidental','Frios','Congelados','🔥 Promoções'].map((s,i)=>`<div class="category-card"><span>${i===8?'🔥':'▦'}</span><b>${s}</b><small>${i===8?'Produtos com preço promocional':'Categoria do catálogo'}</small></div>`).join('')}</div></div>`}
async function promoTab(){const {data,error}=await client.from('products').select('*').order('name');if(error)return $('tab').innerHTML='<div class="notice">'+esc(error.message)+'</div>';products=data||[];$('tab').innerHTML=`${pageTitle('Promoções','Defina ou remova preços promocionais.') }<div class="panel-card"><div class="promo-list">${products.map(p=>`<div class="promo-row"><div class="grow"><b>${esc(p.name)}</b><small>Preço normal: ${money(p.price)} ${p.promo_price!=null?'• Atual: '+money(p.promo_price):''}</small></div><input id="pr_${p.id}" type="number" step="0.01" min="0" value="${p.promo_price??''}" placeholder="Preço oferta"><button class="primary" onclick="setPromo('${p.id}')">Salvar</button></div>`).join('')}</div></div>`}
async function setPromo(id){const v=$(`pr_${id}`).value,p=products.find(x=>x.id===id)||(await client.from('products').select('*').eq('id',id).single()).data;if(v&&Number(v)>=Number(p.price))return alert('O preço promocional deve ser menor que o preço normal.');const {error}=await client.from('products').update({promo_price:v?Number(v):null,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else{alert('Promoção atualizada!');promoTab()}}
async function bannersTab(){const {data,error}=await client.from('site_banners').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:true});if(error){$('tab').innerHTML='<div class="notice">'+esc(error.message)+'</div>';return}const banners=data||[];$('tab').innerHTML=`${pageTitle('Banners','Até 5 banners no topo do site para todos os visitantes.') }<div class="panel-card"><p>Adicione imagens horizontais. Elas aparecem automaticamente no topo do catálogo.</p>${banners.length<5?`<form class="form" id="bf"><label class="full">Imagem do banner<input id="bannerImage" type="file" accept="image/*" required></label><div id="bannerPreview" class="full banner-preview"><span>Selecione uma imagem para visualizar</span></div><button class="primary full">Adicionar banner (${banners.length}/5)</button></form>`:`<div class="notice">Você já possui 5 banners. Remova um para adicionar outro.</div>`}<div class="banner-admin-list">${banners.length?banners.map((b,i)=>`<div class="banner-admin-row"><div class="banner-number">${i+1}</div><img src="${esc(b.image_url)}" alt="Banner ${i+1}" class="banner-admin-img"><div class="grow"><b>Banner ${i+1}</b><small>${b.active?'Visível no site':'Oculto'}</small></div><button class="danger" onclick="removeBanner('${b.id}','${esc(b.storage_path||'')}')">Remover</button></div>`).join(''):'<div class="empty-state">Nenhum banner cadastrado.</div>'}</div></div>`;if($('bf')){$('bannerImage').onchange=()=>{const f=$('bannerImage').files[0];if(!f)return;const url=URL.createObjectURL(f);$('bannerPreview').innerHTML=`<img src="${url}" alt="Pré-visualização">`};$('bf').onsubmit=addBanner}}
async function uploadBanner(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${crypto.randomUUID()}.${ext}`;const {error}=await client.storage.from('banner-images').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return {path,url:client.storage.from('banner-images').getPublicUrl(path).data.publicUrl}}
async function addBanner(e){e.preventDefault();const {count,error:countError}=await client.from('site_banners').select('id',{count:'exact',head:true});if(countError)return alert('Erro: '+countError.message);if((count||0)>=5)return alert('Você pode ter no máximo 5 banners.');const f=$('bannerImage').files[0];if(!f)return alert('Selecione uma imagem.');try{const up=await uploadBanner(f);const {error}=await client.from('site_banners').insert({image_url:up.url,storage_path:up.path,sort_order:count||0,active:true});if(error){await client.storage.from('banner-images').remove([up.path]);throw error}alert('Banner adicionado!');bannersTab()}catch(e){alert('Erro ao adicionar banner: '+e.message)}}
async function removeBanner(id,path){if(!confirm('Remover este banner do site?'))return;const {error}=await client.from('site_banners').delete().eq('id',id);if(error)return alert('Erro: '+error.message);if(path)await client.storage.from('banner-images').remove([path]);const {data}=await client.from('site_banners').select('id').order('sort_order',{ascending:true});if(data)await Promise.all(data.map((b,i)=>client.from('site_banners').update({sort_order:i}).eq('id',b.id)));bannersTab()}
async function clientsTab(){const {data,error}=await client.from('profiles').select('id,email,role,created_at').order('created_at',{ascending:false});if(error){$('tab').innerHTML='<div class="notice">Não foi possível carregar os clientes: '+esc(error.message)+'</div>';return}const clients=data||[];$('tab').innerHTML=`${pageTitle('Clientes','Gerencie as contas cadastradas na loja.') }<div class="metric-grid compact"><div class="metric orange"><span>👥</span><div><small>Total de Clientes</small><strong>${clients.filter(c=>c.role!=='admin').length}</strong><em>Contas de clientes</em></div></div><div class="metric purple"><span>🛡</span><div><small>Administradores</small><strong>${clients.filter(c=>c.role==='admin').length}</strong><em>Contas administrativas</em></div></div></div><div class="panel-card"><div class="toolbar"><input id="clientSearch" placeholder="Buscar por e-mail..." oninput="filterClients()"><select id="clientFilter" onchange="filterClients()"><option value="all">Todas as contas</option><option value="user">Clientes</option><option value="admin">Administradores</option></select></div><div class="table-wrap"><table><thead><tr><th>E-mail</th><th>Tipo</th><th>Data de cadastro</th><th>Ações</th></tr></thead><tbody id="clientRows">${clientRows(clients)}</tbody></table></div></div>`;window.adminClients=clients}
function clientRows(clients){return clients.map(c=>`<tr><td><b>${esc(c.email||'Sem e-mail')}</b></td><td><span class="type-pill ${c.role==='admin'?'admin-pill':''}">${c.role==='admin'?'Administrador':'Cliente'}</span></td><td>${new Date(c.created_at).toLocaleString('pt-BR')}</td><td>${c.id!==currentUserId?`<button class="small-btn" onclick="resetClientPassword('${c.id}','${esc(c.email||'')}')">✉ Redefinir senha</button><button class="small-btn danger-outline" onclick="removeClient('${c.id}','${esc(c.email||'')}')">🗑 Remover</button>`:'<b class="muted">Sua conta</b>'}</td></tr>`).join('')||'<tr><td colspan="4" class="empty-state">Nenhum cliente cadastrado.</td></tr>'}
function filterClients(){const q=($('clientSearch')?.value||'').toLowerCase(),f=$('clientFilter')?.value||'all';const rows=(window.adminClients||[]).filter(c=>(!q||(c.email||'').toLowerCase().includes(q))&&(f==='all'||c.role===f));$('clientRows').innerHTML=clientRows(rows)}
async function resetClientPassword(id,email){if(!email)return alert('Este cliente não possui e-mail cadastrado.');if(!confirm('Enviar um link de redefinição de senha para '+email+'?'))return;const redirectTo=new URL('login.html',window.location.href).href;const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo});if(error)alert('Erro: '+error.message);else alert('Link enviado para '+email+'.')}
async function removeClient(id,email){if(id===currentUserId)return alert('Você não pode remover sua própria conta.');if(!confirm('Remover definitivamente a conta de '+email+'?'))return;const {error}=await client.rpc('admin_delete_user',{target_user_id:id});if(error)return alert('Não foi possível remover: '+error.message);alert('Cliente removido.');clientsTab()}
async function ordersTab(){const {data,error}=await client.from('orders').select('*').order('created_at',{ascending:false});if(error){$('tab').innerHTML='<div class="notice">Não foi possível carregar os pedidos: '+esc(error.message)+'</div>';return}const orders=data||[];$('tab').innerHTML=`${pageTitle('Pedidos','Pedidos feitos pelo site e recebidos diretamente neste painel.') }<div class="order-filters"><button class="filter-btn active" onclick="filterOrders('all',this)">Todos</button><button class="filter-btn" onclick="filterOrders('received',this)">Novos</button><button class="filter-btn" onclick="filterOrders('ready_payment',this)">Prontos para pagar</button><button class="filter-btn" onclick="filterOrders('paid',this)">Pagos</button><button class="filter-btn" onclick="filterOrders('completed',this)">Finalizados</button><button class="filter-btn" onclick="filterOrders('cancelled',this)">Cancelados</button></div><div id="ordersList" class="orders-list">${orders.length?orders.map(orderCard).join(''):'<div class="panel-card empty-state">Nenhum pedido recebido.</div>'}</div>`;window.adminOrders=orders}
function orderCard(o){const items=Array.isArray(o.items)?o.items:[];return `<article class="order-card" data-status="${esc(o.status)}"><div class="order-head"><div><span class="order-number">Pedido #${o.order_number}</span><small>${new Date(o.created_at).toLocaleString('pt-BR')}</small></div><span class="status ${statusClass[o.status]||''}">${statusLabel[o.status]||o.status}</span></div><div class="order-body"><div class="customer-box"><b>Cliente</b><strong>${esc(o.customer_name)}</strong><span>📱 ${esc(o.customer_phone)}</span>${o.customer_email?`<span>✉ ${esc(o.customer_email)}</span>`:''}${o.document_number?`<span>🪪 ${o.document_type==='cnpj'?'CNPJ':'CPF'}: ${esc(o.document_number)}</span>`:''}${o.zipcode?`<span>📍 CEP: ${esc(o.zipcode)}</span>`:''}${o.sales_customer?`<span>💬 Cadastro no WhatsApp de vendas</span>`:''}${o.note?`<div class="note">📝 ${esc(o.note)}</div>`:''}</div><div class="order-items">${items.map(i=>`<div><span>${esc(i.name)} × ${i.qty}</span><strong>${money(i.subtotal)}</strong></div>`).join('')}<div class="order-total"><span>Total</span><strong>${money(o.total)}</strong></div></div></div><div class="order-actions">${o.status==='received'?`<button class="primary" onclick="finalizeAndNotify('${o.id}','${o.customer_phone}','${esc(o.customer_name)}',${o.order_number})">✅ Finalizar e avisar no WhatsApp</button>`:''}${o.status==='ready_payment'?`<button class="primary" onclick="markPaid('${o.id}')">💰 Marcar como pago</button><button class="whatsapp-btn" onclick="contactCustomer('${o.customer_phone}','${esc(o.customer_name)}','ready_payment',${o.order_number})">💬 Avisar para pagar</button>`:''}${o.status==='paid'?`<button class="primary" onclick="markCompleted('${o.id}')">📦 Finalizar pedido</button><button class="whatsapp-btn" onclick="contactCustomer('${o.customer_phone}','${esc(o.customer_name)}','paid',${o.order_number})">💬 Entrar em contato pelo WhatsApp</button>`:''}${o.status==='completed'?`<button class="whatsapp-btn" onclick="contactCustomer('${o.customer_phone}','${esc(o.customer_name)}','completed',${o.order_number})">💬 Contatar cliente</button>`:''}<button class="danger" onclick="cancelOrder('${o.id}')">Cancelar</button></div></article>`}
function filterOrders(status,btn){document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.order-card').forEach(c=>c.style.display=status==='all'||c.dataset.status===status?'block':'none')}
async function markReady(id){const {error}=await client.from('orders').update({status:'ready_payment',updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);ordersTab();refreshOrderBadge()}
async function finalizeAndNotify(id,phone,name,number){const {error}=await client.from('orders').update({status:'ready_payment',updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);refreshOrderBadge();contactCustomer(phone,name,'ready_payment',number);ordersTab()}
async function markPaid(id){const {error}=await client.from('orders').update({status:'paid',updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);ordersTab()}
async function markCompleted(id){const {error}=await client.from('orders').update({status:'completed',updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);ordersTab()}
async function cancelOrder(id){if(!confirm('Cancelar este pedido?'))return;const {error}=await client.from('orders').update({status:'cancelled',updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);ordersTab();refreshOrderBadge()}
function contactCustomer(phone,name,status,number){const p=String(phone||'').replace(/\D/g,'');let msg='';if(status==='ready_payment')msg=`Olá, ${name}! Seu pedido #${number} foi conferido e está pronto para pagamento. Por favor, entre em contato conosco para concluir o pagamento. 🍔`;else if(status==='paid')msg=`Olá, ${name}! Recebemos a confirmação do pagamento do pedido #${number}. Estamos entrando em contato para combinar a entrega/retirada. Obrigado!`;else msg=`Olá, ${name}! Estamos falando sobre o seu pedido #${number} da Macrofood.`;location.href=`https://wa.me/${p}?text=${encodeURIComponent(msg)}`}

async function suggestionsTab(){
  const {data,error}=await client.from('product_suggestions').select('id,user_id,product_name,note,storage_path,created_at').order('created_at',{ascending:false});
  if(error){$('tab').innerHTML='<div class="notice">Não foi possível carregar as sugestões: '+esc(error.message)+'</div>';return}
  const rows=data||[];
  if(!rows.length){
    $('tab').innerHTML=`${pageTitle('Sugestões de clientes','Fotos e sugestões enviadas somente por clientes logados.')}<div class="panel-card empty-state">💡 Nenhuma sugestão recebida ainda.</div>`;
    return;
  }
  const userIds=[...new Set(rows.map(x=>x.user_id).filter(Boolean))];
  let profiles=[];
  if(userIds.length){
    const r=await client.from('profiles').select('id,email,nickname,avatar_url').in('id',userIds);
    profiles=r.data||[];
  }
  const map=new Map(profiles.map(x=>[x.id,x]));
  const cards=await Promise.all(rows.map(async s=>{
    let url='';
    if(s.storage_path){
      const signed=await client.storage.from('product-suggestions').createSignedUrl(s.storage_path,3600);
      url=signed.data?.signedUrl||'';
    }
    const profile=map.get(s.user_id)||{};
    return `<article class="suggestion-card">${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer"><img src="${esc(url)}" alt="Foto sugerida por cliente"></a>`:`<div class="suggestion-image-missing">📷 Foto indisponível</div>`}<div class="suggestion-card-body"><h3>${esc(s.product_name)}</h3><p><b>Cliente:</b> ${esc(profile.nickname||'Cliente')} ${profile.email?`• ${esc(profile.email)}`:''}</p>${s.note?`<p><b>Observação:</b> ${esc(s.note)}</p>`:''}<small>${new Date(s.created_at).toLocaleString('pt-BR')}</small><div class="suggestion-card-actions">${url?`<a class="outline-btn" href="${esc(url)}" target="_blank" rel="noopener noreferrer">🔎 Ver foto</a>`:''}<button class="danger" onclick="removeSuggestion('${s.id}','${esc(s.storage_path||'')}')">🗑 Excluir</button></div></div></article>`;
  }));
  $('tab').innerHTML=`${pageTitle('Sugestões de clientes','Veja as fotos e produtos sugeridos pelos clientes. Essas imagens não aparecem no catálogo público.')}<div class="metric-grid compact"><div class="metric orange"><span>💡</span><div><small>Total de sugestões</small><strong>${rows.length}</strong><em>Enviadas por clientes</em></div></div></div><div class="suggestion-admin-grid">${cards.join('')}</div>`;
}
async function removeSuggestion(id,path){if(!confirm('Excluir esta sugestão e a foto enviada pelo cliente?'))return;const {error}=await client.from('product_suggestions').delete().eq('id',id);if(error)return alert('Não foi possível excluir: '+error.message);if(path)await client.storage.from('product-suggestions').remove([path]);suggestionsTab()}

async function supportTab(){
  const {data:rows,error}=await client.from('support_messages').select('id,user_id,sender_role,message,created_at').order('created_at',{ascending:false});
  if(error){$('tab').innerHTML='<div class="notice">Não foi possível carregar o suporte: '+esc(error.message)+'</div>';return}
  const all=rows||[],ids=[...new Set(all.map(x=>x.user_id).filter(Boolean))];let profiles=[];
  if(ids.length){const r=await client.from('profiles').select('id,email,nickname,avatar_url').in('id',ids);profiles=r.data||[]}
  const {data:states}=await client.from('support_conversations').select('user_id,status,resolved_at').in('user_id',ids.length?ids:['00000000-0000-0000-0000-000000000000']);
  const stateMap=new Map((states||[]).map(x=>[x.user_id,x]));const map=new Map(profiles.map(p=>[p.id,p]));
  const convs=ids.map(uid=>{const list=all.filter(m=>m.user_id===uid);const p=map.get(uid)||{};const st=stateMap.get(uid)||{status:'open'};return {uid,p,last:list[0],count:list.length,status:st.status,resolved_at:st.resolved_at}});
  window.supportRows=all;window.supportProfiles=map;window.supportStates=stateMap;
  $('tab').innerHTML=`${pageTitle('Suporte ao cliente','Converse com clientes e finalize os atendimentos.')}<div class="support-admin-layout"><div class="support-conversations" id="supportConversations">${convs.length?convs.map((c,i)=>`<button class="support-conv ${i===0?'active':''}" onclick="openSupportConversation('${c.uid}',this)"><b>${esc(c.p.nickname||'Cliente')} ${c.status==='resolved'?'<span class="resolved-chip">✓ Resolvido</span>':''}</b><small>${esc(c.p.email||'')} • ${c.count} mensagem(ns)</small><small>${esc((c.last?.message||'').slice(0,70))}</small></button>`).join(''):'<div class="support-empty">Nenhuma conversa ainda.</div>'}</div><div class="admin-chat-card"><div class="admin-chat-head"><div><h3 id="supportChatTitle">${convs.length?esc(convs[0].p.nickname||'Cliente'):'Selecione um cliente'}</h3><small id="supportChatEmail">${convs.length?esc(convs[0].p.email||''):''}</small></div><span id="adminSupportStatus" class="support-status"></span></div><div id="adminChatMessages" class="admin-chat-messages">${convs.length?'':'<div class="support-empty">Selecione uma conversa.</div>'}</div><form id="adminChatForm" class="admin-chat-compose" style="${convs.length?'':'display:none'}"><textarea id="adminChatText" maxlength="1000" placeholder="Digite uma resposta..."></textarea><button class="primary">Enviar</button></form><div id="adminSupportActions" class="admin-support-actions"></div></div></div>`;
  window.selectedSupportUser=window.selectedSupportUser||convs[0]?.uid||null;
  if(window.selectedSupportUser&&convs.some(c=>c.uid===window.selectedSupportUser)){
    const c=convs.find(c=>c.uid===window.selectedSupportUser);activateSupportConversation(c);
  }else if(convs[0]){window.selectedSupportUser=convs[0].uid;activateSupportConversation(convs[0])}
  refreshSupportBadge();
}
function activateSupportConversation(c){
  document.querySelectorAll('.support-conv').forEach(x=>x.classList.remove('active'));
  const btn=[...document.querySelectorAll('.support-conv')].find(x=>x.getAttribute('onclick')?.includes(c.uid));if(btn)btn.classList.add('active');
  window.selectedSupportUser=c.uid;$('supportChatTitle').textContent=c.p.nickname||'Cliente';$('supportChatEmail').textContent=c.p.email||'';renderAdminChat(c.uid);$('adminChatForm').style.display='flex';$('adminChatForm').onsubmit=sendAdminSupport;updateAdminSupportState(c);
}
function openSupportConversation(uid,btn){
  const p=window.supportProfiles.get(uid)||{};const st=window.supportStates?.get(uid)||{status:'open'};activateSupportConversation({uid,p,status:st.status,resolved_at:st.resolved_at});
}
function updateAdminSupportState(c){
  const status=$('adminSupportStatus'),actions=$('adminSupportActions');if(status){status.textContent=c.status==='resolved'?'✓ Problema resolvido':'● Atendimento em andamento';status.className='support-status '+(c.status==='resolved'?'resolved':'open')}
  if(actions)actions.innerHTML=c.status==='resolved'?`<button class="secondary" type="button" onclick="reopenAdminSupport('${c.uid}')">↩ Reabrir conversa</button>`:`<button class="resolve-btn" type="button" onclick="resolveAdminSupport('${c.uid}')">✓ Problema resolvido</button>`;
  const form=$('adminChatForm');if(form)form.style.display='flex';
}
function renderAdminChat(uid){const rows=(window.supportRows||[]).filter(m=>m.user_id===uid).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));$('adminChatMessages').innerHTML=rows.length?rows.map(m=>`<div class="support-msg ${m.sender_role==='admin'?'admin':'user'}">${esc(m.message).replace(/\n/g,'<br>')}<small>${m.sender_role==='admin'?'Administrador':'Cliente'} • ${new Date(m.created_at).toLocaleString('pt-BR')}</small></div>`).join(''):'<div class="support-empty">Nenhuma mensagem.</div>';const el=$('adminChatMessages');el.scrollTop=el.scrollHeight}
async function sendAdminSupport(e){e.preventDefault();const text=$('adminChatText').value.trim(),uid=window.selectedSupportUser;if(!text||!uid)return;const {error}=await client.from('support_conversations').upsert({user_id:uid,status:'open',resolved_at:null,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)return alert(error.message);const {error:sendError}=await client.from('support_messages').insert({user_id:uid,sender_role:'admin',message:text});if(sendError)return alert('Não foi possível enviar: '+sendError.message);$('adminChatText').value='';const {data}=await client.from('support_messages').select('id,user_id,sender_role,message,created_at').order('created_at',{ascending:false});window.supportRows=data||[];if(window.supportStates)window.supportStates.set(uid,{user_id:uid,status:'open'});renderAdminChat(uid);updateAdminSupportState({uid,status:'open'});}
async function resolveAdminSupport(uid){if(!confirm('Marcar esta conversa como problema resolvido?'))return;const {error}=await client.from('support_conversations').upsert({user_id:uid,status:'resolved',resolved_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)return alert('Não foi possível finalizar: '+error.message);window.supportStates.set(uid,{user_id:uid,status:'resolved'});updateAdminSupportState({uid,status:'resolved'});const btn=[...document.querySelectorAll('.support-conv')].find(x=>x.getAttribute('onclick')?.includes(uid));if(btn&&!btn.innerHTML.includes('Resolvido'))btn.querySelector('b').insertAdjacentHTML('beforeend',' <span class="resolved-chip">✓ Resolvido</span>');}
async function reopenAdminSupport(uid){const {error}=await client.from('support_conversations').upsert({user_id:uid,status:'open',resolved_at:null,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)return alert(error.message);window.supportStates.set(uid,{user_id:uid,status:'open'});updateAdminSupportState({uid,status:'open'});}
async function refreshSupportBadge(){const {count}=await client.from('support_messages').select('id',{count:'exact',head:true}).eq('sender_role','user');const b=$('supportBadge');if(b){b.textContent=count||0;b.classList.toggle('hidden',!count)}}
async function refreshSupportConversation(){if(!document.querySelector('[data-nav=\"support\"]')?.classList.contains('active'))return;const {data,error}=await client.from('support_messages').select('id,user_id,sender_role,message,created_at').order('created_at',{ascending:false});if(error)return;window.supportRows=data||[];if(window.selectedSupportUser)renderAdminChat(window.selectedSupportUser);refreshSupportBadge()}
setInterval(refreshSupportConversation,5000)
async function settingsTab(){const {data}=await client.from('site_settings').select('*').eq('key','whatsapp_orders').maybeSingle();$('tab').innerHTML=`${pageTitle('Configurações','Ajustes básicos do atendimento.') }<div class="panel-card"><label>WhatsApp da Macrofood<input id="wa" value="${esc(data?.value||'5581971178793')}" placeholder="5581999999999"></label><button class="primary" onclick="saveWa()">Salvar WhatsApp</button><div class="notice">Os pedidos agora ficam no painel. O WhatsApp é usado somente quando o administrador clicar para avisar ou contatar o cliente.</div></div>`}
async function saveWa(){let v=$('wa').value.replace(/\D/g,'');const {error}=await client.from('site_settings').upsert({key:'whatsapp_orders',value:v});if(error)alert(error.message);else alert('WhatsApp salvo!')}
init();
