const client=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);const sectors=['Todos','Chocolates','Confeitaria','Sorveteria','Restaurante','Ocidental','Resfriados','Congelados'];let active='Todos',products=[],cart=JSON.parse(localStorage.getItem('macrofood_cart')||'[]');const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const $=id=>document.getElementById(id);
function renderCats(){$('cats').innerHTML=sectors.map(s=>`<button class="cat ${s===active?'active':''}" onclick="active='${s}';render()">${s}</button>`).join('')}
async function load(){let {data,error}=await client.from('products').select('*').eq('active',true).order('name');if(error){$('grid').innerHTML=`<div class='notice'>Erro ao carregar catálogo: ${esc(error.message)}</div>`;return}products=data||[];render()}
function stars(p){return `<div class="stars">★★★★★ <small>${Number(p.rating_avg||0).toFixed(1)} (${p.rating_count||0})</small></div>`}
function render(){renderCats();$('cartCount').textContent=cart.reduce((n,x)=>n+x.qty,0);let q=$('search').value.toLowerCase().trim();let list=products.filter(p=>(active==='Todos'||p.sector===active)&&(!q||p.name.toLowerCase().includes(q)||p.sector.toLowerCase().includes(q)));$('grid').innerHTML=list.length?list.map(p=>`<article class="card"><div class="pic">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:'📦'}</div><div class="info"><div class="sector">${esc(p.sector)}</div><div class="name">${esc(p.name)}</div>${p.product_code?`<div class="code">Código: ${esc(p.product_code)}</div>`:''}${p.promo_price!=null?`<div class="oldprice">${money(p.price)}</div><div class="price promo">${money(p.promo_price)}</div><span class="offer">🔥 PROMOÇÃO</span>`:`<div class="price">${money(p.price)}</div>`}${stars(p)}<button class="primary" onclick="addCart('${p.id}')" ${p.in_stock===false?'disabled':''}>${p.in_stock===false?'Sem estoque':'🛒 Adicionar ao carrinho'}</button></div></article>`).join(''):'<div style="grid-column:1/-1;text-align:center;padding:40px;color:#777">Nenhum produto encontrado.</div>'}
function addCart(id){const p=products.find(x=>x.id===id);if(!p||p.in_stock===false)return;const x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id:p.id,name:p.name,price:Number(p.promo_price??p.price),qty:1});localStorage.setItem('macrofood_cart',JSON.stringify(cart));render();openCart()}
function openCart(){ $('cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><span>${esc(x.name)}<br><small>${money(x.price)} × ${x.qty}</small></span><div><button onclick="changeQty(${i},-1)">−</button> ${x.qty} <button onclick="changeQty(${i},1)">+</button></div></div>`).join('')+'<h3>Total: '+money(cart.reduce((s,x)=>s+x.price*x.qty,0))+'</h3>':'<p>Seu carrinho está vazio.</p>';$('cartModal').style.display='flex'}
function closeCart(){$('cartModal').style.display='none'}function changeQty(i,d){cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);localStorage.setItem('macrofood_cart',JSON.stringify(cart));openCart();render()}
async function checkoutWhatsApp(){if(!cart.length)return alert('Carrinho vazio.');let {data}=await client.from('site_settings').select('value').eq('key','whatsapp_orders').maybeSingle();let phone=(data?.value||'5581971178793').replace(/\D/g,'');let text='Olá Macrofood! Quero fazer este pedido:%0A'+cart.map(x=>`• ${x.name} x${x.qty} - ${money(x.price*x.qty)}`).join('%0A')+'%0A%0ATotal: '+money(cart.reduce((s,x)=>s+x.price*x.qty,0));location.href=`https://wa.me/${phone}?text=${text}`}
load();document.querySelector('.search span')?.addEventListener('click',openCart)
