const client=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
const sectors=["Todos","Chocolates","Confeitaria","Sorveteria","Restaurante","Ocidental","Resfriados","Congelados"];let active="Todos",products=[],cart=[],settings={whatsapp:"81971178793"},banners=[],reviewProductId=null,reviewRating=5;
const money=v=>Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function load(){
 const [pr,se,ba]=await Promise.all([client.from("products").select("*").eq("active",true).order("name"),client.from("site_settings").select("key,value"),client.from("banners").select("*").eq("active",true).order("sort_order")]);
 if(pr.error){document.getElementById("grid").innerHTML="<div class='notice'>Erro ao carregar produtos: "+esc(pr.error.message)+"</div>";return} products=pr.data||[];
 if(!se.error)(se.data||[]).forEach(x=>settings[x.key]=x.value); banners=ba.error?[]:(ba.data||[]); renderSettings();renderBanners();render();
}
function renderSettings(){const n=(settings.whatsapp||"").replace(/\D/g,"");const a=document.getElementById("footerWhats");a.textContent=n;a.href=n?`https://wa.me/${n}`:"#"}
function renderBanners(){document.getElementById("banners").innerHTML=banners.length?`<div class="bannerTrack">${banners.map(b=>`<div class="banner"><img src="${esc(b.image_url)}" alt="${esc(b.title||"")}">${b.title?`<div>${esc(b.title)}</div>`:""}</div>`).join("")}</div>`:""}
function renderCats(){document.getElementById("cats").innerHTML=sectors.map(s=>`<button class="cat ${s===active?"active":""}" onclick="active='${s}';render()">${s}</button>`).join("")}
function render(){renderCats();let q=document.getElementById("search").value.toLowerCase().trim();let list=products.filter(p=>(active==="Todos"||p.sector===active)&&(!q||p.name.toLowerCase().includes(q)||p.sector.toLowerCase().includes(q)));let promos=list.filter(p=>p.promotion&&Number(p.old_price)>Number(p.price));document.getElementById("promoArea").innerHTML=active==="Todos"&&promos.length?`<section><h2 class="sectionTitle">🔥 Promoções</h2><div class="promoGrid">${promos.map(card).join("")}</div></section>`:"";document.getElementById("grid").innerHTML=list.length?`<h2 class="sectionTitle">${active==="Todos"?"Produtos":""}</h2>`+list.map(card).join(""):"<div class='notice'>Nenhum produto encontrado.</div>"}
function card(p){let stars="★★★★★";return `<article class="card"><div class="pic">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:"📦"}${p.promotion?`<span class="promoTag">OFERTA</span>`:""}${!p.in_stock?`<span class="stockTag">SEM ESTOQUE</span>`:""}</div><div class="info"><div class="sector">${esc(p.sector)}</div><div class="name">${esc(p.name)}</div>${p.product_code?`<div class="code">Código: ${esc(p.product_code)}</div>`:""}<div class="rating" id="rating-${p.id}">${stars}</div>${p.promotion?`<div class="oldPrice">De: ${money(p.old_price)}</div>`:""}<div class="price">${money(p.price)}</div><div class="actions"><button class="buy" ${!p.in_stock?"disabled":""} onclick="addCart('${p.id}')">${p.in_stock?"🛒 Adicionar":"Sem estoque"}</button><button class="review" onclick="openReview('${p.id}','${esc(p.name)}')">⭐ Avaliar</button></div></div></article>"}
function addCart(id){let p=products.find(x=>x.id===id);if(!p||!p.in_stock)return;let x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({...p,qty:1});updateCart()}
function updateCart(){document.getElementById("cartCount").textContent=cart.reduce((s,x)=>s+x.qty,0)}
function openCart(){document.getElementById("cartModal").style.display="flex";document.getElementById("cartItems").innerHTML=cart.length?cart.map((p,i)=>`<div class="cartRow"><span>${esc(p.name)} x${p.qty}</span><b>${money(p.price*p.qty)}</b><button onclick="cart.splice(${i},1);updateCart();openCart()">✕</button></div>`).join(""):"<p>Carrinho vazio.</p>";document.getElementById("cartTotal").textContent=cart.length?"Total: "+money(cart.reduce((s,p)=>s+p.price*p.qty,0)):""}
function closeCart(){document.getElementById("cartModal").style.display="none"}
function sendWhatsApp(){if(!cart.length)return alert("Adicione produtos ao carrinho.");let n=(settings.whatsapp||"").replace(/\D/g,"");if(!n)return alert("O administrador ainda não cadastrou o WhatsApp para pedidos.");let lines=cart.map(p=>`• ${p.name} x${p.qty} — ${money(p.price*p.qty)}`).join("\n");let total=cart.reduce((s,p)=>s+p.price*p.qty,0);let msg=`Olá! Gostaria de fazer este pedido na Macrofood:\n\n${lines}\n\nTotal: ${money(total)}`;window.open(`https://wa.me/${n}?text=${encodeURIComponent(msg)}`,"_blank")}
function openReview(id,name){reviewProductId=id;reviewRating=5;document.getElementById("reviewProduct").textContent=name;document.getElementById("reviewText").value="";document.getElementById("stars").textContent="★★★★★";document.getElementById("reviewModal").style.display="flex"}
function closeReview(){document.getElementById("reviewModal").style.display="none"}
document.getElementById("stars").addEventListener("click",e=>{let r=Math.max(1,Math.min(5,Math.round((e.offsetX/e.currentTarget.clientWidth)*5)));reviewRating=r;e.currentTarget.textContent="★★★★★"})
async function submitReview(){let text=document.getElementById("reviewText").value.trim();let {error}=await client.from("reviews").insert({product_id:reviewProductId,rating:reviewRating,comment:text||null});if(error)return alert("Não foi possível enviar: "+error.message);alert("Obrigado pela avaliação!");closeReview()}
load();
